import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientLayout from "./ClientLayout";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "RentEase - Rent and List Your apartments",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/toplogo.png" type="image/png" />
      </head>
      <body>
        <ClientLayout>
          <Navbar />
          <ToastContainer
            position="top-right"
            autoClose={2000}
            style={{ marginTop: "4rem" }}
          />
          {children}
          <Footer />
        </ClientLayout>
      </body>
    </html>
  );
}
